### ISSUE TITLE
The format of images influence the detection results

### ISSUE THREAD

**Issue by shanshuo** [wangkaihong/HADM#2]
Hi, thanks for your contribution for solving the human artifact detection. It's very meaningful for the community. When I run the inference on [this image](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fmidjourney-are-you-good-at-hands-yet-v0-6rpvhoop1e6b1.png%3Fauto%3Dwebp%26s%3D1d2dac7ee7c54b166ca5eaf6570d9bc56f353ad6l), if I save it as PNG and then [inference](https://github.com/wangkaihong/HADM?tab=readme-ov-file#local-human-artifact-detection-model-hadm-l), the hand score is 0.4269. If I use the following way to convert the PNG to JPEG and feed it to HADM-L, the score becomes 0.2484. There is an obvious gap, though from human eyes the two images are almost the same.
```Python
from PIL import Image

img = Image.open(png_path)
img.convert('RGB').save(jpg_path, 'JPEG')
```

I think the reason might be that the training set is JPEG and the model learning some [artifacts](https://forums.fast.ai/t/whats-the-difference-between-training-on-jpeg-and-png/4029/2) caused by JPEG. So maybe remind people to use JPEG in README to avoid the mismatch.

**Comment by wangkaihong** [comment]
Thanks for the reminder!
